[package]
name = "e3wm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = {version="1.2.0",features=["randr"]}
api = {version="0.1.0",path="../api/"}
xkbcommon={version="0.5.0"}
